### ISSUE TITLE
How to run this locally?

### ISSUE THREAD

**Issue by vinamelody** [openshift-quickstart/openshift-ghost-quickstart#64]
Hi, the deployment is easy but how to run this locally on Mac? I keep getting error 

```
Unhandled rejection Error: Cannot find module '/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Client_SQLite3.initDriver (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:41:24)
    at new Client_SQLite3 (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:15:10)
    at Knex.initialize (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/knex/knex.js:109:15)
    at Knex (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/knex/knex.js:13:26)
    at ConfigManager.set (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/core/server/config/index.js:156:24)
    at ConfigManager.init (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/core/server/config/index.js:79:10)
    at /Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/core/server/config/index.js:273:30
    at tryCatcher (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local/node_modules/ghost/node_modules/bluebird/js/main/promise.js:697:14)
```

**Comment by MunGell** [comment]
Hey @vinamelody 

It is failing because we don't have `node_modules/ghost/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node` file in the repository. 

`sqlite3` module has different versions of it for different platforms, this repository contains linux version, which makes it work on OpenShift. To run Ghost on your Mac you need to reinstall `sqlite3` for `darwin` platform.

```
$ cd node_modules/ghost/
$ npm i sqlite3
```

This will update sqlite3 module to work on your machine, just don't commit it to the repository, otherwise it will brake your OpenShift site.

**Comment by vinamelody** [comment]
Hi @MunGell, i did what you suggested but still getting the same error. Is there anything else needs to be changed related to this module?

**Comment by MunGell** [comment]
This is strange, could you please delete whole `node_modules` directory and run `npm install` again?

**Comment by vinamelody** [comment]
I tried deleting and `npm install` gives me this error

```
> ghost@0.7.8 preinstall /Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local-sqlite/node_modules/.staging/ghost-c2036f1e
> npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

ghost@0.7.8 /Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local-sqlite/node_modules/.staging/ghost-c2036f1e
└── semver@5.1.0

npm WARN openshift-ghost-quickstart@ No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.12
npm ERR! npm  v3.8.2
npm ERR! path /Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local-sqlite/node_modules/ghost/node_modules/semver
npm ERR! code ENOTEMPTY
npm ERR! errno -66

npm ERR! ENOTEMPTY, rename '/Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local-sqlite/node_modules/ghost/node_modules/semver'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vinamelody/Code/vinamelody-openshift/ghost/hikari-local-sqlite/npm-debug.log
```

**Comment by MunGell** [comment]
I've just tried to do the same on my local with code from this repository and it did work as expected...
Sorry, I am not sure how to help you, maybe someone else here or in Ghost community will know how to fix it.

**Comment by vinamelody** [comment]
@MunGell it worked when I use local postgresql :) .. skip sqlite and thank you for your help!

**Comment by MunGell** [comment]
Cool, glad you figured that out :)
